### PR TITLE
ft: This PR enable password reset feature for user

### LINKED ISSUE #20: User rest password
# Description:

As a user, I should be able to reset the password for my account if I have forgotten it. This feature will enhance user experience by providing a straightforward and secure way to regain access to accounts.

## User Story:

- Title: Reset Password
As a user, I should be able to reset my password if I forget it.

### Reset Password Link:

- A "Forgot Password?" link should be available on the login page.
- Clicking the link should redirect to a password reset request page.

### Password Reset Request Page:

- The user should be prompted to enter their registered email address.
- The system should validate the email format and check if it exists in the database.
- Upon validation, a reset password email containing a secure token and reset instructions should be sent.

### Reset Password Email:

- The email should include a secure token or a link with the token embedded.
- The token should be valid for a limited time (e.g., 1 hour) and be single-use.

### Token Validation Page:

- The page should extract and validate the token from the URL.
- The system should check if the token is valid and not expired.
- Appropriate error messages should be displayed if the token is invalid or expired.

### Reset Password Form:

- The form should allow the user to enter and confirm a new password.
- Both password fields should be validated to ensure they match.
- The new password should meet strength requirements (e.g., minimum length, inclusion of numbers and special characters).

### Password Update:

- The user's password should be updated in the database upon successful validation.
- The user should receive a confirmation message indicating the password has been reset.
- Optionally, an email notification should be sent to the user confirming the password change.

### Post-Reset Actions:

- The user should be redirected to the login page to log in with the new password.
- The system should provide an option to request a new reset link if the token is invalid or expired.

## Design Considerations:

- *Security:* Ensure the entire reset process is secure to prevent unauthorized access.
- *Usability:* Design the process to be straightforward and user-friendly.
- *Accessibility:* Make sure the reset password functionality is accessible to all users, including those using assistive technologies.
- 
By implementing this functionality, we ensure users have a reliable and secure method to regain access to their accounts, thereby improving the overall user experience and security of our e-commerce platform.

### PR DESCRIPTION
**Pull request by Ndevu12**
This Pull Request introduces the password reset feature for users. This is an essential feature that allows users who have forgotten their passwords to easily reset them and regain access to their accounts.

## Changes include:

- `Password Reset Request:` Users can request a password reset from the login page. An email will be sent to the user's registered email address with a password reset link.

- `Password Reset Page:` A new page where users can enter a new password after clicking the password reset link in their email.

- `Backend Changes:` Updates to the backend to handle password reset requests and update the user's password in the database.

- `Tests:` Unit and integration tests have been added to ensure the feature works as expected.

This feature enhances the user experience by providing an easy and secure way for users to reset their passwords.

# Visual Representation

## Forgot Password

Screen Shot 2024-06-24 at 19 53 14
Screen Shot 2024-06-24 at 19 53 01

## Reset Password

Screen Shot 2024-06-24 at 19 55 37
Screen Shot 2024-06-24 at 19 55 31

### CODE REVIEW

**Comment by faid-terence** [comment]
@Ndevu12 
Please attach screenshots of your pages !!

**Comment by Ndevu12** [comment]
> @Ndevu12 Please attach screenshots of your pages !!

Done

**Review by aimedivin — APPROVED** [review]

**Review by UwicyezaG — APPROVED** [review]

**Comment by aimedivin** [comment]
@Ndevu12 , Remember to use the rounded buttons and for forgot password page Use correct font size for title 'Forgot your password?'

**Comment by faid-terence** [comment]
@Ndevu12 
Fix isssues on forgot password page on the desktop version.

**Review by GSinseswa721 — APPROVED** [review]

**Review by Calebgisa72 — APPROVED** [review]

**Comment by Calebgisa72** [comment]
@Ndevu12, I see according to the screenshots some elements on the mobile version are not properly aligned the same way in the figma design

**Review by faid-terence — APPROVED** [review]
Nice Work @Ndevu12 !

**Pull request merged**
