### PR TITLE
Protecting  routes

### LINKED ISSUE #66: Protected routes
Protect routes
Render dashboard according to logge in user

### PR DESCRIPTION
**Pull request by elijahladdie**

### CODE REVIEW

**Comment by faid-terence** [comment]
@elijahladdie 
Reabse with develop to resolve conflicts !

**Comment by elijahladdie** [comment]
> @elijahladdie Reabse with develop to resolve conflicts !

@faid-terence Done

**Comment by elijahladdie** [comment]
> > @elijahladdie Reabse with develop to resolve conflicts !
> 
> @faid-terence On it

**Review by MC-Knight — APPROVED** [review]

**Review by UwicyezaG — APPROVED** [review]

**Review by GSinseswa721 — APPROVED** [review]

**Review by faid-terence — APPROVED** [review]
Nice Work @elijahladdie 
PR Approved !!

**Pull request merged**
