### PR TITLE
Chore: configure husky, eslint and prettier

### LINKED ISSUE #3: Configure ESLint and Prettier && Set Up Pre-commit Hooks
- Ensure code quality and consistency by setting up linting and formatting tools.
 - Implement pre-commit hooks using Husky to check linting and code formatting before commits.
 - Install Husky: `npm install husky --save-dev`

### PR DESCRIPTION
**Pull request by elijahladdie**
### Description
 This PR is for husky pre-commit config that will enable us to fix linting and code formatting using prettier every time developer commits changes to git

### Functionalities

1. Lint and format when committing
   - When you run `git commit -m "commit message"` or `git commit --amend --no-edit` your codes are automatically formatted to improve code readability and maintainability
### Acceptance criteria
 
- [x] Lints and formats are automatically applied before every commit

### CODE REVIEW

**Comment by faid-terence** [comment]
@elijahladdie and @Ndevu12 
Write a clear description for this PR !

**Review by Calebgisa72 — APPROVED** [review]

**Review by faid-terence — APPROVED** [review]
Nice Work @elijahladdie !

**Comment by elijahladdie** [comment]
> Nice Work @elijahladdie !

@faid-terence thanks

**Comment by Ndevu12** [comment]
# Implementation plan:

- Choose and install linting (ESLint) and formatting (Prettier) tools.
- Install Husky for Git hooks.
- Configure linting and formatting rules.
- Integrate linting and formatting tools to work together.
- Set up Husky pre-commit hook with lint-staged to check staged files.
- Add npm scripts for manual linting and formatting.
- Test the setup, document the process, and inform the team.

The plan focuses on setting up tools to automatically enforce code quality and consistency before each commit, reducing manual effort and potential errors.

**Pull request merged**
