### PR TITLE
ft: user should be able to provide a review after order is complete

### LINKED ISSUE #49: A buyer should be able to leave feedback/reviews for products
Description
Why

Buyers should be able to share their thoughts on products they have purchased in order to help future buyers make informed decisions.

Acceptance Criteria:

GIVEN that the buyer has purchased a product

WHEN the buyer visits the product page
THEN they should see an option to leave a review
GIVEN that the buyer is leaving a review

WHEN they submit the review form
THEN the review should be saved and displayed on the product page along with other reviews
Dev Notes:

Only buyers who have purchased the product should be able to leave a review.
The form for leaving a review should include fields for rating, title, and comment.
Review moderation should be implemented to prevent inappropriate content.

### PR DESCRIPTION
**Pull request by elijahladdie**
# Description:

This PR introduces a new feature that allows users to submit a review after an order has been completed.

## Changes include:

- A new FeedbackForm component that captures user input for the review. This includes a comment field that the user can fill out to provide their review.

- The FeedbackForm component is integrated into the existing order completion workflow. After an order is marked as complete, the user is presented with the FeedbackForm.

- Form validation is implemented to ensure that the comment field is not left empty.

- Upon form submission, the review data is sent to the backend for processing.

This feature enhances the user experience by allowing users to provide feedback on their orders, which can help other users make informed decisions about their purchases.

### CODE REVIEW

**Comment by faid-terence** [comment]
@elijahladdie , @Ndevu12 
What's the progress on this PR ??

**Comment by Ndevu12** [comment]
> @elijahladdie , @Ndevu12 
> What's the progress on this PR ??

@faid-terence We are working on tests

**Comment by faid-terence** [comment]
@elijahladdie @Ndevu12 
Please increase the coverage !

**Comment by elijahladdie** [comment]
Yes @faid-terence

**Comment by faid-terence** [comment]
@elijahladdie and @Ndevu12 
Squash the commit message as well !
They should not be more than 2!

**Comment by elijahladdie** [comment]
> @elijahladdie and @Ndevu12 
> Squash the commit message as well !
> They should not be more than 2!

Noted @faid-terence

**Comment by faid-terence** [comment]
@elijahladdie and @Ndevu12 
What's  the progress man ?

**Comment by Ndevu12** [comment]
> @elijahladdie and @Ndevu12 
> What's  the progress man ?

We are trying to increase test coverage Sir.

**Review by MC-Knight — APPROVED** [review]

**Review by UwicyezaG — APPROVED** [review]

**Review by faid-terence — APPROVED** [review]
PR Approved @elijahladdie and @Ndevu12 !
Good Job !

**Pull request merged**
